<a href="https://colab.research.google.com/github/ANIKETKURWADE/ANIKET/blob/main/Q3_Singular_Value_Decomposition_(SVD)_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Q3. Singular Value Decomposition (SVD):**

In [ ]:
import numpy as np

np.random.seed(24)
A = np.random.randint(0, 10, size=(5, 5))

# Perform Singular Value Decomposition (SVD) on matrix A
U, Sigma, Vt = np.linalg.svd(A)
print("Matrix U:")
print(U)
print("\nMatrix Sigma (Diagonal matrix):")
print(np.diag(Sigma))
print("\nMatrix Vt (Transpose of V):")
print(Vt)
A_reconstructed = np.dot(U, np.dot(np.diag(Sigma), Vt))
print("\nIs A equal to the product of U, Sigma, and Vt? ", np.allclose(A, A_reconstructed))

# Rank 2 approximation of matrix A
rank_2_approximation = np.dot(U[:, :2], np.dot(np.diag(Sigma[:2]), Vt[:2, :]))
print("\nRank 2 approximation of matrix A:")
print(rank_2_approximation)

# Rank 3 approximation of matrix A
rank_3_approximation = np.dot(U[:, :3], np.dot(np.diag(Sigma[:3]), Vt[:3, :]))
print("\nRank 3 approximation of matrix A:")
print(rank_3_approximation)


Matrix U:
[[-0.31711551  0.19846944  0.82724069 -0.09481079  0.40832755]
 [-0.28636832  0.01911614 -0.37353972  0.58437361  0.66075965]
 [-0.5422238  -0.5295216  -0.2310952  -0.58640564  0.16829636]
 [-0.60444462  0.67412143 -0.22587358 -0.06239895 -0.35396962]
 [-0.39758142 -0.47477534  0.26780041  0.54932066 -0.49299811]]

Matrix Sigma (Diagonal matrix):
[[21.51927588  0.          0.          0.          0.        ]
 [ 0.          6.88343047  0.          0.          0.        ]
 [ 0.          0.          4.56497988  0.          0.        ]
 [ 0.          0.          0.          2.0233148   0.        ]
 [ 0.          0.          0.          0.          1.2674014 ]]

Matrix Vt (Transpose of V):
[[-0.1493515  -0.34820317 -0.3439167  -0.71489023 -0.47655214]
 [ 0.10245686  0.47505882  0.39689141  0.07303988 -0.77521874]
 [ 0.08039556  0.02225248 -0.76687284  0.55216021 -0.31633294]
 [-0.44622674 -0.66561451  0.34142267  0.42140426 -0.25236489]
 [ 0.87270555 -0.45775083  0.13976807  0.033